### ISSUE TITLE
Create Register, Homepage Pages using Styled-components

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#1]
Create a good looking registration and homepage design

1.  Register Page 
2.  HomePage where we about collegeReboot and playstore app ui design where it is wriiten app comming soon

Strong Knowlege of vanilla CSS and styled-components Required

**Comment by ShaziahGafur** [comment]
Hi @Ayushpanditmoto, I can work on this feature. Can you assign this issue to me?

**Comment by Ayushpanditmoto** [comment]
@ShaziahGafur  I am assigning you for homepage page landing screen just create a demo homepage


> Hi @Ayushpanditmoto, I can work on this feature. Can you assign this issue to me?
Sure I am assigning this task to you, if you face any issues or want to ask something about the project feel free to ask here. Happy Coding 🚀
