### ISSUE TITLE
Create a forgot password page

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#10]
This is beginner friendly task

**Comment by DevAttaKhan** [comment]
**I would like to contribute.**

**Comment by Ayushpanditmoto** [comment]
@DevAttaKhan   you have done a great job now can you add your name WantToContribute.md file add your name here

**Comment by Ayushpanditmoto** [comment]
@DevAttaKhan  please create one more pull request as i m not able to see your name in contributor list
