### ISSUE TITLE
Fix Date of birth ,branch and gender is required error handling with formik on touch component in signup page

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#12]
In client side it show user is not 18+, gender is required and branch is required with formik touch

**Comment by dineshigdd** [comment]
hi, I would like to contribute to your project

**Comment by Ayushpanditmoto** [comment]
I am assigning this Task

**Comment by dineshigdd** [comment]
Thank You very much. I will work on it

**Comment by dineshigdd** [comment]
I already fixed the issue with the branch field.

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  
1. Default branch is master
2.  In birth date you have to check person should be greater than 18+ warning

**Comment by dineshigdd** [comment]
ok..sorry, when I was asking about the branch, I mean the branch (university branch in the app) in the application. Anyway, I fixed the issue regarding the "select" field.

**Comment by Ayushpanditmoto** [comment]
Actually there is no default branch you can ard initial value  length 0 after that see whether is more than 0 if not then show error

**Comment by dineshigdd** [comment]
Do you want me to make PR after I fixed everything or after I fixed a particular control on the form?

**Comment by Ayushpanditmoto** [comment]
2nd option will be better

**Comment by dineshigdd** [comment]
I added functions to display error msg for branch and gender controls on the signup page.  I make my PR to the beta branch

**Comment by Ayushpanditmoto** [comment]
nice work @dineshigdd

**Comment by dineshigdd** [comment]
Thank you . I will work on birthday issue too. Hopefully I can make a PR on Tuesday.

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  nice you are doing great work

**Comment by dineshigdd** [comment]
I sent a new PR for Birthday error msgs

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  thank you for contributing
