### ISSUE TITLE
Create a Reset password Page [UI part]

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#19]
After forgot password user 
User have to option to Enter new password 
Confirm new password type of page

**Comment by sanjana-1604** [comment]
Hi, I would like to work on this issue. Please assign it to me.

**Comment by Ayushpanditmoto** [comment]
@sanjana-1604  But remember 
1. you have to use styled-components to design the UI.
2. Go through this video its 1 hour tutorial
https://www.youtube.com/watch?v=02zO0hZmwnw&t=2304s

**Comment by Ayushpanditmoto** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/31253617/208810242-f4f407b9-3102-4787-8668-f5e4ac4fe009.png)

@dineshigdd  you can solve this issue

This Reset page will be available in 
https://localhost:3000/reset 
Route

**Comment by dineshigdd** [comment]
I will

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  Thank you bro for contributing on this project, i hope in january end we will complete this project

**Comment by sanjana-1604** [comment]
Hello Ayush,Is Dinesh working on the reset page?
    On Wednesday, December 21, 2022 at 03:00:37 AM GMT, Ayush Kumar Pandit ***@***.***> wrote:  
 
 




@dineshigdd you can solve this issue

This Reset page will be available in
https://localhost:3000/reset
Route

**Comment by Ayushpanditmoto** [comment]
Currently @dineshigdd  is working on this 
but @sanjana-1604  you can work on Readme file

1. I am also trying to be consistent on this project, i will raise more issues 
2.  Currently our Registration and login part completly done .

**Comment by dineshigdd** [comment]
Yes..I am working on

**Comment by sanjana-1604** [comment]
okay, I had done some structuring for ReadMe but I need data to fill in the topics.
If you have any documents related to all the features please provide me.
    On Wednesday, December 21, 2022 at 02:44:11 PM GMT, Ayush Kumar Pandit ***@***.***> wrote:  
 
 


Currently @dineshigdd is working on this
but @sanjana-1604 you can work on Readme file
   
   - I am also trying to be consistent on this project, i will raise more issues
   - Currently our Registration and login part completly done .

**Comment by dineshigdd** [comment]
Just to make sure after resetting the password, is the user supposed to redirect to the Login page or profile page?

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  you can redirect  to login page

**Comment by sanjana-1604** [comment]
Hello Ayush,Pushed an initial draft of README.Review the content under all the headings and provide missing data to enter.  
    On Wednesday, December 21, 2022 at 04:31:34 PM GMT, Ayush Kumar Pandit ***@***.***> wrote:  
 
 


@dineshigdd you can redirect to login page

**Comment by Ayushpanditmoto** [comment]
@sanjana-1604  you can add infos like
1. how to clone this project and start 
2.  add a new Screenshot 
3.  You can what this website is about write what ever you want 

if i found any thing is missing we both edit those changes

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  thank you dinesh i am closing this issues as this solved by you ,thank you for contributing

**Comment by dineshigdd** [comment]
Always a pleasure 🙏 to help you as best as I can
