### ISSUE TITLE
Improve the Readme Documentation

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#22]
Create a beautiful Readme Documentation

**Comment by sanjana-1604** [comment]
HI I can help here

**Comment by Ayushpanditmoto** [comment]
@sanjana-1604  I am assigning this task to you

**Comment by Rishav1707** [comment]
Shall I work on this issue? @Ayushpanditmoto

**Comment by Ayushpanditmoto** [comment]
@Rishav1707  sure, i m assigning this task
