### ISSUE TITLE
In Login Page Add Password Visibilty and invisibilty icons with show and hide password feature

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#28]

**Comment by Rishav1707** [comment]
Shall I work on this issue? @Ayushpanditmoto

**Comment by Ayushpanditmoto** [comment]
@Rishav1707  sure

**Comment by dineshigdd** [comment]
is @Rishav1707 working on this?

**Comment by Ayushpanditmoto** [comment]
@Rishav1707 are you working on this issue ??

**Comment by JohnnyOhms** [comment]
i think i can work on this issue and deliver the solution in few hours, assign it to me pls

**Comment by Rishav1707** [comment]
> @Rishav1707 are you working on this issue ??

No, please assign this issue to someone

**Comment by dineshigdd** [comment]
Ok. then I will work on it

**Comment by dineshigdd** [comment]
There was an merge conflict

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  i resolved the merge conflict

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  i am closing this issue as you completed this task

**Comment by dineshigdd** [comment]
@Ayushpanditmoto . I think I found a minor issue here with the toggling of the eye. The default should be the closed eyes. Would you please make an new issue so that I can make it correct and make a new PR
