### ISSUE TITLE
empty page after login

### ISSUE THREAD

**Issue by ozair-dev** [Ayushpanditmoto/CollegeReboot#30]
after I login to the website, I only see an empty page,

and the email verification link takes me to a page with this error
![Screenshot from 2022-12-21 23-47-42](https://user-images.githubusercontent.com/65649182/208981081-9d2ca9a2-6ba4-412b-96ff-e6369d95efb7.png)

**Comment by Ayushpanditmoto** [comment]
We will work on this issue later 
1. 1stly we have to create when we login we redirect to our social media posts pages
2. Now we will start working this social media posts pages
3. After that we will work on this  activation issue

**Comment by ozair-dev** [comment]
Do you already know about this error?
![Screenshot from 2022-12-22 00-17-02](https://user-images.githubusercontent.com/65649182/208986087-5086cbfa-47cd-42ff-a9b7-5492c9c6d98f.png)

I tried going to different pages (profile, not found) etc but I see the same empty screen and the same error

**Comment by Ayushpanditmoto** [comment]
@ozair-dev  last two error can be ignored these are from server side i removed mapping

but 1st one i think i have debug the issue

**Comment by ozair-dev** [comment]
hmm ok
