### ISSUE TITLE
Mobile Responsive Reset password Page

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#33]
https://college-reboot.vercel.app/reset

![Screenshot_7](https://user-images.githubusercontent.com/31253617/208991960-20fbeede-7416-4ac2-8836-bb9b141e985d.png)

**Comment by Ayushpanditmoto** [comment]
@dineshigdd  would you like to work on this issue?

**Comment by dineshigdd** [comment]
yes...sure I think I forgot to test it for mobiles

**Comment by dineshigdd** [comment]
made a new PR

**Comment by Derryck2020** [comment]
Would like to work on it

**Comment by Rishav1707** [comment]
Shall I work on this issue? @Ayushpanditmoto

**Comment by Ayushpanditmoto** [comment]
![Screenshot_2022-12-22-09-00-28-262_com android chrome](https://user-images.githubusercontent.com/31253617/209049635-69976602-310e-4ac0-a110-a4a83b14a3fc.jpg)
 

Add left right margin

**Comment by Ayushpanditmoto** [comment]
Make sure you work on beta branch

**Comment by Ayushpanditmoto** [comment]
I am Closing this issue as this issue is fixed
