### ISSUE TITLE
i need to be part of this community

### ISSUE THREAD

**Issue by JohnnyOhms** [Ayushpanditmoto/CollegeReboot#35]
Pls i need to be part of this community, pls approve my cotributions to the frontend issues

**Comment by Ayushpanditmoto** [comment]
@JohnnyOhms create a Not Found page

**Comment by JohnnyOhms** [comment]
Ok sir, working on it

**Comment by JohnnyOhms** [comment]
i opened a pull request for the issue you stated, pls review

**Comment by Ayushpanditmoto** [comment]
@JohnnyOhms solve the merge conflict
