### ISSUE TITLE
Implement redux folder structure on the project

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#4]
The project is using simple folder structure, but since we will have to deals with lot of components it is becoming more and more difficult to maintain without redux. Implement redux folder structure on the frontend side of the project.

![redux](https://user-images.githubusercontent.com/31253617/205506984-ab4b54aa-c9a8-451f-bf82-1863bc404b74.jpg)

**Comment by phryneas** [comment]
Just make sure you mean [this folder structure](https://redux.js.org/style-guide/#structure-files-as-feature-folders-with-single-file-logic) by that, not that old actions/reducers/constants folder thingy :)

**Comment by phryneas** [comment]
I just gave you a link to the official Redux Style Guide which contains an example folder structure?

![image](https://user-images.githubusercontent.com/4282439/205508786-a23c745f-8bec-47ba-a712-a51d9f2e76cf.png)

**Comment by Ayushpanditmoto** [comment]
This task completed my me so i am closing this issue
