### ISSUE TITLE
Create a reset your password page 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#48]
![Screenshot_2](https://user-images.githubusercontent.com/31253617/210841027-929133eb-592b-4953-af24-59bf29254a84.png)

**Comment by dineshigdd** [comment]
ok ..I will do it. basically, you want to change the existing UI at https://college-reboot.vercel.app/reset ?

**Comment by dineshigdd** [comment]
Ok...I will do it as soon as possible with my availability, and try my best to make a PR by Sunday.

**Comment by dineshigdd** [comment]
just want to give you an update. I will make PR on Monday after I completed the responsive design.

**Comment by Ayushpanditmoto** [comment]
@dineshigdd you are doing great job
